name: Advanced CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Check Python version
        run: python --version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest flake8

      - name: List files in workspace (debug)
        run: |
          pwd
          ls -R
          cat test_app.py
          cat conftest.py || echo "No conftest.py found"

      - name: Run pytest
        run: pytest -v --capture=tee-sys

      - name: Code quality check
        run: flake8 .
